server {
    listen 80;
    server_name loveladybaptist.com www.loveladybaptist.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name loveladybaptist.com www.loveladybaptist.com;

    ssl_certificate     /etc/letsencrypt/live/loveladybaptist.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/loveladybaptist.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # API Routing
    location ^~ /api/v1/ {
        proxy_pass http://the-fasting-ox-python-django-api:8001;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Static Files
    location ^~ /static/ {
        alias /usr/share/nginx/html/django_static/;
    }

    # API Admin Portal
    location ^~ /admin/ {
        proxy_pass http://the-fasting-ox-python-django-api:8001;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React Frontend Router
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # React Assets Caching
    location ~* ^(?!/(api|admin|static/)).*\.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }
}
